<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright 2026 Mishmash IO UK Ltd.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.mishmash.stacks</groupId>
    <artifactId>distributed-computing-stacks</artifactId>
    <version>1.0.3</version>
    <relativePath>../../../pom.xml</relativePath>
  </parent>

  <groupId>io.mishmash.stacks.patches</groupId>
  <artifactId>arrow-flight-core-patches</artifactId>
  <version>${arrow.stable.version}-mmio.${arrow.stable.mishmash.io.patch}.${arrow.stable.mishmash.io.update}</version>
  <packaging>jar</packaging>

  <name>mishmash io patches of Apache Arrow Flight RPC core</name>
  <description>
    This package contains Apache Arrow code as modified by mishmash io. For more info 
    on the specific modifications by mishmash io visit our website and GitHub.

    It is recommended that you don't use this package directly, but rather - one or more of the 
    minimal distributed memory stacks packages.
  </description>
  <url>https://mishmash.io/open_source/distributed-computing-stacks</url>

  <licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
  </licenses>

  <organization>
    <name>mishmash io</name>
    <url>https://mishmash.io</url>
  </organization>

  <scm>
    <connection>scm:git:https://github.com/mishmash-io/distributed-computing-stacks.git</connection>
    <developerConnection>scm:git:https://github.com/mishmash-io/distributed-computing-stacks.git</developerConnection>
    <url>https://github.com/mishmash-io/distributed-computing-stacks</url>
  </scm>

  <developers>
    <developer>
      <name>Ivan Kountchev</name>
      <email>i.kountchev@mishmash.io</email>
      <organization>mishmash io</organization>
      <organizationUrl>https://mishmash.io</organizationUrl>
      <roles>
        <role>developer</role>
      </roles>
    </developer>
    <developer>
      <name>Andrey Rusev</name>
      <email>a.rusev@mishmash.io</email>
      <url>www.linkedin.com/in/andrey-rusev-21894172</url>
      <organization>mishmash io</organization>
      <organizationUrl>https://mishmash.io</organizationUrl>
      <roles>
        <role>architect</role>
      </roles>
    </developer>
  </developers>

  <properties>
    <grpc.version>1.80.0</grpc.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.mishmash.stacks.patches</groupId>
        <artifactId>arrow-memory-core-patches</artifactId>
        <version>${arrow.stable.version}-mmio.${arrow.stable.mishmash.io.patch}.${arrow.stable.mishmash.io.update}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.mishmash.stacks.patches</groupId>
        <artifactId>arrow-memory-core-patches</artifactId>
        <version>${arrow.stable.version}-mmio.${arrow.stable.mishmash.io.patch}.${arrow.stable.mishmash.io.update}</version>
      </dependency>
      <dependency>
        <groupId>io.mishmash.stacks.patches</groupId>
        <artifactId>arrow-vector-patches</artifactId>
        <version>${arrow.stable.version}-mmio.${arrow.stable.mishmash.io.patch}.${arrow.stable.mishmash.io.update}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.mishmash.stacks.patches</groupId>
        <artifactId>arrow-vector-patches</artifactId>
        <version>${arrow.stable.version}-mmio.${arrow.stable.mishmash.io.patch}.${arrow.stable.mishmash.io.update}</version>
      </dependency>
      <dependency>
        <groupId>io.mishmash.stacks.patches</groupId>
        <artifactId>arrow-vector-patches</artifactId>
        <version>${arrow.stable.version}-mmio.${arrow.stable.mishmash.io.patch}.${arrow.stable.mishmash.io.update}</version>
        <scope>test</scope>
        <classifier>tests</classifier>
      </dependency>
      <dependency>
        <groupId>io.mishmash.stacks.patches</groupId>
        <artifactId>arrow-memory-netty-patches</artifactId>
        <version>${arrow.stable.version}-mmio.${arrow.stable.mishmash.io.patch}.${arrow.stable.mishmash.io.update}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>io.mishmash.stacks.patches</groupId>
        <artifactId>arrow-memory-netty-patches</artifactId>
        <version>${arrow.stable.version}-mmio.${arrow.stable.mishmash.io.patch}.${arrow.stable.mishmash.io.update}</version>
      </dependency>
      <dependency>
        <groupId>io.grpc</groupId>
        <artifactId>grpc-bom</artifactId>
        <version>${grpc.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protobuf-java</artifactId>
        <version>${protobuf.version}</version>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protobuf-java-util</artifactId>
        <version>${protobuf.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>io.mishmash.stacks.patches</groupId>
      <artifactId>arrow-memory-core-patches</artifactId>
    </dependency>
    <dependency>
      <groupId>io.mishmash.stacks.patches</groupId>
      <artifactId>arrow-vector-patches</artifactId>
    </dependency>
    <dependency>
      <groupId>io.mishmash.stacks.patches</groupId>
      <artifactId>arrow-memory-netty-patches</artifactId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>org.immutables</groupId>
      <artifactId>value-annotations</artifactId>
      <scope>provided</scope> <!-- compile only -->
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-netty</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-protobuf</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-buffer</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler</artifactId>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-stub</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java-util</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>

    <dependency>
      <groupId>io.mishmash.stacks.patches</groupId>
      <artifactId>arrow-vector-patches</artifactId>
      <scope>test</scope>
      <classifier>tests</classifier>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-services</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-inprocess</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-core</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>com.googlecode.maven-download-plugin</groupId>
        <artifactId>download-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>download-patch</id>
            <phase>initialize</phase>
            <goals>
              <goal>wget</goal>
            </goals>
            <configuration>
              <url>https://github.com/mishmash-io/arrow-java/compare/v${arrow.stable.version}...mishmash-io:arrow-java:patch-${arrow.stable.version}_${arrow.stable.mishmash.io.patch}.diff</url>
              <outputFileName>mishmash_io_arrow.patch</outputFileName>
              <outputDirectory>${project.build.directory}</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>download-original-source</id>
            <phase>initialize</phase>
            <goals>
              <goal>wget</goal>
            </goals>
            <configuration>
              <url>https://github.com/apache/arrow-java/archive/refs/tags/v${arrow.stable.version}.zip</url>
              <unpack>true</unpack>
              <outputDirectory>${project.build.directory}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-patch-plugin</artifactId>
        <executions>
          <execution>
            <id>patch-original-source</id>
            <phase>initialize</phase>
            <goals>
              <goal>apply</goal>
            </goals>
            <configuration>
              <patchFile>${project.build.directory}/mishmash_io_arrow.patch</patchFile>
              <patchTrackingFile>${project.build.directory}/mishmash_io_arrow_changes.txt</patchTrackingFile>
              <strip>1</strip>
              <removeEmptyFiles>true</removeEmptyFiles>
              <targetDirectory>${project.build.directory}/arrow-java-${arrow.stable.version}</targetDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-arrow-sources</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <!-- add the patched arrow-flight-core soruces -->
                <source>${project.build.directory}/arrow-java-${arrow.stable.version}/flight/flight-core/src/main/java</source>
                <!--source>/home/zethix/git/mishmash-github/arrow-java/flight/flight-core/src/main/java</source-->
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-arrow-test-sources</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <!-- add the patched arrow-flight-core test soruces -->
                <source>${project.build.directory}/arrow-java-${arrow.stable.version}/flight/flight-core/src/test/java</source>
                <source>${project.build.directory}/arrow-java-${arrow.stable.version}/flight/flight-core/src/test/proto</source>
              </sources>
            </configuration>
          </execution>
          <execution>
            <id>add-arrow-test-resources</id>
            <phase>generate-test-resources</phase>
            <goals>
              <goal>add-test-resource</goal>
            </goals>
            <configuration>
              <resources>
                <!-- add the test resoruces -->
                <resource>
                  <directory>
                    ${project.build.directory}/arrow-java-${arrow.stable.version}/flight/flight-core/src/test/resources
                  </directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.xolstice.maven.plugins</groupId>
        <artifactId>protobuf-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>compile-protobuf</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>compile</goal>
              <goal>compile-custom</goal>
            </goals>
            <configuration>
              <protoSourceRoot>${project.build.directory}/arrow-java-${arrow.stable.version}/arrow-format/</protoSourceRoot>
              <pluginId>grpc-java</pluginId>
              <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
              <pluginParameter>@generated=omit</pluginParameter>
            </configuration>
          </execution>
          <execution>
            <id>compile-tests-protobuf</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>test-compile</goal>
              <goal>test-compile-custom</goal>
            </goals>
            <configuration>
              <protoTestSourceRoot>${project.build.directory}/arrow-java-${arrow.stable.version}/flight/flight-core/src/test/proto</protoTestSourceRoot>
              <pluginId>grpc-java</pluginId>
              <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}</pluginArtifact>
              <pluginParameter>@generated=omit</pluginParameter>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths combine.children="append">
            <path>
              <groupId>org.immutables</groupId>
              <artifactId>value</artifactId>
              <version>${immutables.version}</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
      <!-- package and attach a jar of all sources with patches applied. Do it before tests are run as they run inside the same dir (and create files in it) -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <executions>
          <execution>
            <id>package-patched-sources</id>
            <phase>process-test-classes</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <jar destfile="${project.build.directory}/${project.artifactId}-${project.version}-patched-sources.jar"
                      basedir="${project.build.directory}/arrow-java-${arrow.stable.version}"
                      includes="**"/>
                <attachartifact file="${project.build.directory}/${project.artifactId}-${project.version}-patched-sources.jar" classifier="patched-sources" type="jar"/>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.spdx</groupId>
        <artifactId>spdx-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-gpg-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-deploy-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
