name: Release assets

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-assets:
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: mishmash-io/github-workflows/.github/workflows/maven_build_with_provenance.yml@5ce9b4780f24164bae37a876db7d9444267525ce
    secrets: inherit
    with:
      java-version: 25
      jextract-enable: true
      skip-tests: true
