name: Release assets

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-assets:
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: mishmash-io/github-workflows/.github/workflows/maven_build_with_provenance.yml@207c9eef50bf57e96af0a6ce9b07f19aa722b0e0
    secrets: inherit
    with:
      java-version: 25
      skip-tests: true
