name: Release assets

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-assets:
    permissions:
      contents: write
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: mishmash-io/github-workflows/.github/workflows/maven_build_with_provenance.yml@e21da65d86e3a697ccb967f08f50ddb781b9f10e
    secrets: inherit
    with:
      java-version: 25
      skip-tests: true
